use isla_lib::zencode;

/// 根据扩展名获取对应的 clause 列表
/// 数据来源：sail-riscv 模型中各扩展目录下的 clause 定义
pub fn get_extension_clauses(extension: &str) -> Vec<String> {
    match extension {
        // === 基础扩展 ===
        "i" => [
            "ADDIW",
            "BTYPE",
            "EBREAK",
            "ECALL",
            "FENCE",
            "FENCE_TSO",
            "ITYPE",
            "JAL",
            "JALR",
            "LOAD",
            "MRET",
            "RTYPE",
            "RTYPEW",
            "SFENCE_VMA",
            "SHIFTIOP",
            "SHIFTIWOP",
            "SRET",
            "STORE",
            "UTYPE",
            "WFI",
        ]
        .into_iter()
        .map(|n| zencode::encode(n))
        .collect(),
        "m" => ["DIV", "DIVW", "MUL", "MULW", "REM", "REMW"].into_iter().map(|n| zencode::encode(n)).collect(),
        "a" => ["AMO", "LOADRES", "STORECON"].into_iter().map(|n| zencode::encode(n)).collect(),
        "c" => [
            "C_ADD",
            "C_ADDI",
            "C_ADDI16SP",
            "C_ADDI4SPN",
            "C_ADDIW",
            "C_ADDW",
            "C_AND",
            "C_ANDI",
            "C_BEQZ",
            "C_BNEZ",
            "C_EBREAK",
            "C_J",
            "C_JAL",
            "C_JALR",
            "C_JR",
            "C_LBU",
            "C_LD",
            "C_LDSP",
            "C_LH",
            "C_LHU",
            "C_LI",
            "C_LUI",
            "C_LW",
            "C_LWSP",
            "C_MUL",
            "C_MV",
            "C_NOP",
            "C_NOT",
            "C_OR",
            "C_SB",
            "C_SD",
            "C_SDSP",
            "C_SEXT_B",
            "C_SEXT_H",
            "C_SH",
            "C_SLLI",
            "C_SRAI",
            "C_SRLI",
            "C_SUB",
            "C_SUBW",
            "C_SW",
            "C_SWSP",
            "C_XOR",
            "C_ZEXT_B",
            "C_ZEXT_H",
            "C_ZEXT_W",
        ]
        .into_iter()
        .map(|n| zencode::encode(n))
        .collect(),
        "fd" => [
            "C_FLD",
            "C_FLDSP",
            "C_FLW",
            "C_FLWSP",
            "C_FSD",
            "C_FSDSP",
            "C_FSW",
            "C_FSWSP",
            "F_BIN_F_TYPE_D",
            "F_BIN_F_TYPE_H",
            "F_BIN_RM_TYPE_D",
            "F_BIN_RM_TYPE_H",
            "F_BIN_RM_TYPE_S",
            "F_BIN_TYPE_F_S",
            "F_BIN_TYPE_X_S",
            "F_BIN_X_TYPE_D",
            "F_BIN_X_TYPE_H",
            "FCVTMOD_W_D",
            "FLEQ_D",
            "FLEQ_H",
            "FLEQ_S",
            "FLI_D",
            "FLI_H",
            "FLI_S",
            "FLTQ_D",
            "FLTQ_H",
            "FLTQ_S",
            "F_MADD_TYPE_D",
            "F_MADD_TYPE_H",
            "F_MADD_TYPE_S",
            "FMAXM_D",
            "FMAXM_H",
            "FMAXM_S",
            "FMINM_D",
            "FMINM_H",
            "FMINM_S",
            "FMVH_X_D",
            "FMVP_D_X",
            "FROUND_D",
            "FROUND_H",
            "FROUNDNX_D",
            "FROUNDNX_H",
            "FROUNDNX_S",
            "FROUND_S",
            "F_UN_F_TYPE_D",
            "F_UN_F_TYPE_H",
            "F_UN_RM_FF_TYPE_D",
            "F_UN_RM_FF_TYPE_H",
            "F_UN_RM_FF_TYPE_S",
            "F_UN_RM_FX_TYPE_D",
            "F_UN_RM_FX_TYPE_H",
            "F_UN_RM_FX_TYPE_S",
            "F_UN_RM_XF_TYPE_D",
            "F_UN_RM_XF_TYPE_H",
            "F_UN_RM_XF_TYPE_S",
            "F_UN_TYPE_F_S",
            "F_UN_TYPE_X_S",
            "F_UN_X_TYPE_D",
            "F_UN_X_TYPE_H",
            "LOAD_FP",
            "STORE_FP",
        ]
        .into_iter()
        .map(|n| zencode::encode(n))
        .collect(),

        // === 位操作扩展 ===
        "b" => [
            "CLMUL",
            "CLMULH",
            "CLMULR",
            "CLZ",
            "CLZW",
            "CPOP",
            "CPOPW",
            "CTZ",
            "CTZW",
            "ORCB",
            "REV8",
            "RORI",
            "RORIW",
            "SLLIUW",
            "ZBA_RTYPE",
            "ZBA_RTYPEUW",
            "ZBB_EXTOP",
            "ZBB_RTYPE",
            "ZBB_RTYPEW",
            "ZBS_IOP",
            "ZBS_RTYPE",
        ]
        .into_iter()
        .map(|n| zencode::encode(n))
        .collect(),

        // === 密码学扩展 ===
        "k" => [
            "AES32DSI",
            "AES32DSMI",
            "AES32ESI",
            "AES32ESMI",
            "AES64DS",
            "AES64DSM",
            "AES64ES",
            "AES64ESM",
            "AES64IM",
            "AES64KS1I",
            "AES64KS2",
            "BREV8",
            "SHA256SIG0",
            "SHA256SIG1",
            "SHA256SUM0",
            "SHA256SUM1",
            "SHA512SIG0",
            "SHA512SIG0H",
            "SHA512SIG0L",
            "SHA512SIG1",
            "SHA512SIG1H",
            "SHA512SIG1L",
            "SHA512SUM0",
            "SHA512SUM0R",
            "SHA512SUM1",
            "SHA512SUM1R",
            "SM3P0",
            "SM3P1",
            "SM4ED",
            "SM4KS",
            "UNZIP",
            "XPERM4",
            "XPERM8",
            "ZBKB_PACKW",
            "ZBKB_RTYPE",
            "ZIP",
        ]
        .into_iter()
        .map(|n| zencode::encode(n))
        .collect(),

        // === 向量扩展 ===
        "v" => [
            "FVFMATYPE",
            "FVFMTYPE",
            "FVFTYPE",
            "FVVMATYPE",
            "FVVMTYPE",
            "FVVTYPE",
            "FWFTYPE",
            "FWVFMATYPE",
            "FWVFTYPE",
            "FWVTYPE",
            "FWVVMATYPE",
            "FWVVTYPE",
            "MASKTYPEI",
            "MASKTYPEV",
            "MASKTYPEX",
            "MMTYPE",
            "MOVETYPEI",
            "MOVETYPEV",
            "MOVETYPEX",
            "MVVCOMPRESS",
            "MVVMATYPE",
            "MVVTYPE",
            "MVXMATYPE",
            "MVXTYPE",
            "NISTYPE",
            "NITYPE",
            "NVSTYPE",
            "NVTYPE",
            "NXSTYPE",
            "NXTYPE",
            "RFVVTYPE",
            "RFWVVTYPE",
            "RIVVTYPE",
            "RMVVTYPE",
            "VCPOP_M",
            "VEXTTYPE",
            "VFIRST_M",
            "VFMERGE",
            "VFMV",
            "VFMVFS",
            "VFMVSF",
            "VFNUNARY0",
            "VFUNARY0",
            "VFUNARY1",
            "VFWUNARY0",
            "VICMPTYPE",
            "VID_V",
            "VIMCTYPE",
            "VIMSTYPE",
            "VIMTYPE",
            "VIOTA_M",
            "VISG",
            "VITYPE",
            "VLRETYPE",
            "VLSEGFFTYPE",
            "VLSEGTYPE",
            "VLSSEGTYPE",
            "VLXSEGTYPE",
            "VMSBF_M",
            "VMSIF_M",
            "VMSOF_M",
            "VMTYPE",
            "VMVRTYPE",
            "VMVSX",
            "VMVXS",
            "VSETIVLI",
            "VSETVL",
            "VSETVLI",
            "VSRETYPE",
            "VSSEGTYPE",
            "VSSSEGTYPE",
            "VSXSEGTYPE",
            "VVCMPTYPE",
            "VVMCTYPE",
            "VVMSTYPE",
            "VVMTYPE",
            "VVTYPE",
            "VXCMPTYPE",
            "VXMCTYPE",
            "VXMSTYPE",
            "VXMTYPE",
            "VXSG",
            "VXTYPE",
            "WMVVTYPE",
            "WMVXTYPE",
            "WVTYPE",
            "WVVTYPE",
            "WVXTYPE",
            "WXTYPE",
        ]
        .into_iter()
        .map(|n| zencode::encode(n))
        .collect(),

        // === 向量密码学扩展 ===
        "vector_crypto" => [
            "VAESDF",
            "VAESDM",
            "VAESEF",
            "VAESEM",
            "VAESKF1_VI",
            "VAESKF2_VI",
            "VAESZ_VS",
            "VANDN_VV",
            "VANDN_VX",
            "VBREV8_V",
            "VBREV_V",
            "VCLMULH_VV",
            "VCLMULH_VX",
            "VCLMUL_VV",
            "VCLMUL_VX",
            "VCLZ_V",
            "VCPOP_V",
            "VCTZ_V",
            "VGHSH_VV",
            "VGMUL_VV",
            "VREV8_V",
            "VROL_VV",
            "VROL_VX",
            "VROR_VI",
            "VROR_VV",
            "VROR_VX",
            "VSHA2MS_VV",
            "VSM3C_VI",
            "VSM3ME_VV",
            "VSM4K_VI",
            "VWSLL_VI",
            "VWSLL_VV",
            "VWSLL_VX",
            "ZVKSHA2TYPE",
            "ZVKSM4RTYPE",
        ]
        .into_iter()
        .map(|n| zencode::encode(n))
        .collect(),

        // === BFloat16 扩展 ===
        "bfloat16" => {
            ["FCVT_BF16_S", "FCVT_S_BF16", "VFNCVTBF16_F_F_W", "VFWCVTBF16_F_F_V", "VFWMACCBF16_VF", "VFWMACCBF16_VV"]
                .into_iter()
                .map(|n| zencode::encode(n))
                .collect()
        }

        // === 系统与特权 ===
        "sys" => ["C_ILLEGAL", "ILLEGAL"].into_iter().map(|n| zencode::encode(n)).collect(),
        "svinval" => {
            ["SFENCE_INVAL_IR", "SFENCE_W_INVAL", "SINVAL_VMA"].into_iter().map(|n| zencode::encode(n)).collect()
        }
        "cfi" => ["LPAD"].into_iter().map(|n| zencode::encode(n)).collect(),
        "zawrs" => ["WRS"].into_iter().map(|n| zencode::encode(n)).collect(),

        // === Zicsr 系列扩展 ===
        "zicsr" => ["CSRImm", "CSRReg"].into_iter().map(|n| zencode::encode(n)).collect(),
        "zifencei" => ["FENCEI"].into_iter().map(|n| zencode::encode(n)).collect(),

        // === Zicond 条件扩展 ===
        "zicond" => ["ZICOND_RTYPE"].into_iter().map(|n| zencode::encode(n)).collect(),

        // === 缓存操作扩展 ===
        "zicbom" => ["ZICBOM"].into_iter().map(|n| zencode::encode(n)).collect(),
        "zicbop" => ["ZICBOP"].into_iter().map(|n| zencode::encode(n)).collect(),
        "zicboz" => ["ZICBOZ"].into_iter().map(|n| zencode::encode(n)).collect(),

        // === 提示类扩展 ===
        "zihintntl" => ["C_NTL", "NTL"].into_iter().map(|n| zencode::encode(n)).collect(),
        "zihintpause" => ["PAUSE"].into_iter().map(|n| zencode::encode(n)).collect(),

        // === 自定义指令扩展 ===
        "zcmop" => ["ZCMOP"].into_iter().map(|n| zencode::encode(n)).collect(),
        "zimop" => ["ZIMOP_MOP_R", "ZIMOP_MOP_RR"].into_iter().map(|n| zencode::encode(n)).collect(),
        "zibi" => ["BITYPE"].into_iter().map(|n| zencode::encode(n)).collect(),

        // === Zvabd 向量绝对差扩展 ===
        "zvabd" => ["VABS_V", "ZVABDTYPE", "ZVWABDATYPE"].into_iter().map(|n| zencode::encode(n)).collect(),

        _ => vec![],
    }
}
