ALL=ADDIW AES32DSI AES32DSMI AES32ESI AES32ESMI AES64DS AES64DSM \
AES64ES AES64ESM AES64IM AES64KS1I AES64KS2 AMO BITYPE BREV8 BTYPE \
CLMUL CLMULH CLMULR CLZ CLZW CPOP CPOPW CSRImm CSRReg CTZ CTZW C_ADD \
C_ADDI C_ADDI16SP C_ADDI4SPN C_ADDIW C_ADDW C_AND C_ANDI C_BEQZ \
C_BNEZ C_EBREAK C_FLD C_FLDSP C_FLW C_FLWSP C_FSD C_FSDSP C_FSW \
C_FSWSP C_ILLEGAL C_J C_JAL C_JALR C_JR C_LBU C_LD C_LDSP C_LH \
C_LHU C_LI C_LUI C_LW C_LWSP C_MUL C_MV C_NOP C_NOT C_NTL C_OR \
C_SB C_SD C_SDSP C_SEXT_B C_SEXT_H C_SH C_SLLI C_SRAI C_SRLI \
C_SUB C_SUBW C_SW C_SWSP C_XOR C_ZEXT_B C_ZEXT_H C_ZEXT_W DIV \
DIVW EBREAK ECALL FCVTMOD_W_D FCVT_BF16_S FCVT_S_BF16 FENCE \
FENCEI FENCE_TSO FLEQ_D FLEQ_H FLEQ_S FLI_D FLI_H FLI_S FLTQ_D \
FLTQ_H FLTQ_S FMAXM_D FMAXM_H FMAXM_S FMINM_D FMINM_H \
FMINM_S FMVH_X_D FMVP_D_X FROUNDNX_D FROUNDNX_H FROUNDNX_S \
FROUND_D FROUND_H FROUND_S FVFMATYPE FVFMTYPE FVFTYPE FVVMATYPE \
FVVMTYPE FVVTYPE FWFTYPE FWVFMATYPE FWVFTYPE FWVTYPE FWVVMATYPE \
FWVVTYPE F_BIN_F_TYPE_D F_BIN_F_TYPE_H F_BIN_RM_TYPE_D \
F_BIN_RM_TYPE_H F_BIN_RM_TYPE_S F_BIN_TYPE_F_S F_BIN_TYPE_X_S \
F_BIN_X_TYPE_D F_BIN_X_TYPE_H F_MADD_TYPE_D F_MADD_TYPE_H \
F_MADD_TYPE_S F_UN_F_TYPE_D F_UN_F_TYPE_H F_UN_RM_FF_TYPE_D \
F_UN_RM_FF_TYPE_H F_UN_RM_FF_TYPE_S F_UN_RM_FX_TYPE_D \
F_UN_RM_FX_TYPE_H F_UN_RM_FX_TYPE_S F_UN_RM_XF_TYPE_D \
F_UN_RM_XF_TYPE_H F_UN_RM_XF_TYPE_S F_UN_TYPE_F_S F_UN_TYPE_X_S \
F_UN_X_TYPE_D F_UN_X_TYPE_H ILLEGAL ITYPE JAL JALR LOAD LOADRES \
LOAD_FP LPAD MASKTYPEI MASKTYPEV MASKTYPEX MMTYPE MOVETYPEI \
MOVETYPEV MOVETYPEX MRET MUL MULW MVVCOMPRESS MVVMATYPE MVVTYPE \
MVXMATYPE MVXTYPE NISTYPE NITYPE NTL NVSTYPE NVTYPE NXSTYPE \
NXTYPE ORCB PAUSE REM REMW REV8 RFVVTYPE RFWVVTYPE RIVVTYPE \
RMVVTYPE RORI RORIW RTYPE RTYPEW SFENCE_INVAL_IR SFENCE_VMA \
SFENCE_W_INVAL SHA256SIG0 SHA256SIG1 SHA256SUM0 SHA256SUM1 \
SHA512SIG0 SHA512SIG0H SHA512SIG0L SHA512SIG1 SHA512SIG1H \
SHA512SIG1L SHA512SUM0 SHA512SUM0R SHA512SUM1 SHA512SUM1R \
SHIFTIOP SHIFTIWOP SINVAL_VMA SLLIUW SM3P0 SM3P1 SM4ED SM4KS \
SRET STORE STORECON STORE_FP UNZIP UTYPE VABS_V VAESDF VAESDM \
VAESEF VAESEM VAESKF1_VI VAESKF2_VI VAESZ_VS VANDN_VV VANDN_VX \
VBREV8_V VBREV_V VCLMULH_VV VCLMULH_VX VCLMUL_VV VCLMUL_VX \
VCLZ_V VCPOP_M VCPOP_V VCTZ_V VEXTTYPE VFIRST_M VFMERGE VFMV \
VFMVFS VFMVSF VFNCVTBF16_F_F_W VFNUNARY0 VFUNARY0 VFUNARY1 \
VFWCVTBF16_F_F_V VFWMACCBF16_VF VFWMACCBF16_VV VFWUNARY0 \
VGHSH_VV VGMUL_VV VICMPTYPE VID_V VIMCTYPE VIMSTYPE VIMTYPE \
VIOTA_M VISG VITYPE VLRETYPE VLSEGFFTYPE VLSEGTYPE VLSSEGTYPE \
VLXSEGTYPE VMSBF_M VMSIF_M VMSOF_M VMTYPE VMVRTYPE VMVSX VMVXS \
VREV8_V VROL_VV VROL_VX VROR_VI VROR_VV VROR_VX VSETIVLI VSETVL \
VSETVLI VSHA2MS_VV VSM3C_VI VSM3ME_VV VSM4K_VI VSRETYPE \
VSSEGTYPE VSSSEGTYPE VSXSEGTYPE VVCMPTYPE VVMCTYPE VVMSTYPE \
VVMTYPE VVTYPE VWSLL_VI VWSLL_VV VWSLL_VX VXCMPTYPE VXMCTYPE \
VXMSTYPE VXMTYPE VXSG VXTYPE WFI WMVVTYPE WMVXTYPE WRS WVTYPE \
WVVTYPE WVXTYPE WXTYPE XPERM4 XPERM8 ZBA_RTYPE ZBA_RTYPEUW \
ZBB_EXTOP ZBB_RTYPE ZBB_RTYPEW ZBKB_PACKW ZBKB_RTYPE ZBS_IOP \
ZBS_RTYPE ZCMOP ZICBOM ZICBOP ZICBOZ ZICOND_RTYPE ZIMOP_MOP_R \
ZIMOP_MOP_RR ZIP ZVABDTYPE ZVKSHA2TYPE ZVKSM4RTYPE ZVWABDATYPE 

build-isarch:
	cargo build --release --bin isarch
solve-%: build-isarch
	cargo fmt && cp log log.1 \
		&&cargo build --release --bin isarch \
		&& bash -c "RUST_BACKTRACE=1 ./target/release/isarch \
		-A ./rv64d.ir -C ./configs/riscv64_difftest.toml --verbose --debug=fmlgcsra --probe-all --trace-all --itrace=output/itrace.txt solve-state --clause=$* > $*.log 2> >(tee -a log >&2) "

SOLVE_TARGETS=$(addprefix solve-,$(ALL))

.PHONY: build-isarch solve
solve: $(SOLVE_TARGETS)
