# sail-riscv extension: V
# 89 instruction clauses

INSTRUCTIONS = {
    "FVFMATYPE": [
        "vfmacc.vf",
        "vfmadd.vf",
        "vfmsac.vf",
        "vfmsub.vf",
        "vfnmacc.vf",
        "vfnmadd.vf",
        "vfnmsac.vf",
        "vfnmsub.vf",
    ],
    "FVFMTYPE": [
        "vmfeq.vf",
        "vmfge.vf",
        "vmfgt.vf",
        "vmfle.vf",
        "vmflt.vf",
        "vmfne.vf",
    ],
    "FVFTYPE": [
        "vfadd.vf",
        "vfdiv.vf",
        "vfmax.vf",
        "vfmin.vf",
        "vfmul.vf",
        "vfrdiv.vf",
        "vfrsub.vf",
        "vfsgnj.vf",
        "vfsgnjn.vf",
        "vfsgnjx.vf",
        "vfslide1down.vf",
        "vfslide1up.vf",
        "vfsub.vf",
    ],
    "FVVMATYPE": [
        "vfmacc.vv",
        "vfmadd.vv",
        "vfmsac.vv",
        "vfmsub.vv",
        "vfnmacc.vv",
        "vfnmadd.vv",
        "vfnmsac.vv",
        "vfnmsub.vv",
    ],
    "FVVMTYPE": [
        "vmfeq.vv",
        "vmfle.vv",
        "vmflt.vv",
        "vmfne.vv",
    ],
    "FVVTYPE": [
        "vfadd.vv",
        "vfdiv.vv",
        "vfmax.vv",
        "vfmin.vv",
        "vfmul.vv",
        "vfsgnj.vv",
        "vfsgnjn.vv",
        "vfsgnjx.vv",
        "vfsub.vv",
    ],
    "FWFTYPE": [
        "vfwadd.wf",
        "vfwsub.wf",
    ],
    "FWVFMATYPE": [
        "vfwmacc.vf",
        "vfwmsac.vf",
        "vfwnmacc.vf",
        "vfwnmsac.vf",
    ],
    "FWVFTYPE": [
        "vfwadd.vf",
        "vfwmul.vf",
        "vfwsub.vf",
    ],
    "FWVTYPE": [
        "vfwadd.wv",
        "vfwsub.wv",
    ],
    "FWVVMATYPE": [
        "vfwmacc.vv",
        "vfwmsac.vv",
        "vfwnmacc.vv",
        "vfwnmsac.vv",
    ],
    "FWVVTYPE": [
        "vfwadd.vv",
        "vfwmul.vv",
        "vfwsub.vv",
    ],
    "MASKTYPEI": [
        "vmerge.vim",
    ],
    "MASKTYPEV": [
        "vmerge.vvm",
    ],
    "MASKTYPEX": [
        "vmerge.vxm",
    ],
    "MMTYPE": [
        "vmand.mm",
        "vmandn.mm",
        "vmnand.mm",
        "vmnor.mm",
        "vmor.mm",
        "vmorn.mm",
        "vmxnor.mm",
        "vmxor.mm",
    ],
    "MOVETYPEI": [
        "vmv.v.i",
    ],
    "MOVETYPEV": [
        "vmv.v.v",
    ],
    "MOVETYPEX": [
        "vmv.v.x",
    ],
    "MVVCOMPRESS": [
        "vcompress.vm",
    ],
    "MVVMATYPE": [
        "vmacc.vv",
        "vmadd.vv",
        "vnmsac.vv",
        "vnmsub.vv",
    ],
    "MVVTYPE": [
        "vaadd.vv",
        "vaaddu.vv",
        "vasub.vv",
        "vasubu.vv",
        "vdiv.vv",
        "vdivu.vv",
        "vmul.vv",
        "vmulh.vv",
        "vmulhsu.vv",
        "vmulhu.vv",
        "vrem.vv",
        "vremu.vv",
    ],
    "MVXMATYPE": [
        "vmacc.vx",
        "vmadd.vx",
        "vnmsac.vx",
        "vnmsub.vx",
    ],
    "MVXTYPE": [
        "vaadd.vx",
        "vaaddu.vx",
        "vasub.vx",
        "vasubu.vx",
        "vdiv.vx",
        "vdivu.vx",
        "vmul.vx",
        "vmulh.vx",
        "vmulhsu.vx",
        "vmulhu.vx",
        "vrem.vx",
        "vremu.vx",
        "vslide1down.vx",
        "vslide1up.vx",
    ],
    "NISTYPE": [
        "vnsra.wi",
        "vnsrl.wi",
    ],
    "NITYPE": [
        "vnclip.wi",
        "vnclipu.wi",
    ],
    "NVSTYPE": [
        "vnsra.wv",
        "vnsrl.wv",
    ],
    "NVTYPE": [
        "vnclip.wv",
        "vnclipu.wv",
    ],
    "NXSTYPE": [
        "vnsra.wx",
        "vnsrl.wx",
    ],
    "NXTYPE": [
        "vnclip.wx",
        "vnclipu.wx",
    ],
    "RFVVTYPE": [
        "vfredmax.vs",
        "vfredmin.vs",
        "vfredosum.vs",
        "vfredusum.vs",
    ],
    "RFWVVTYPE": [
        "vfwredosum.vs",
        "vfwredusum.vs",
    ],
    "RIVVTYPE": [
        "vwredsum.vs",
        "vwredsumu.vs",
    ],
    "RMVVTYPE": [
        "vredand.vs",
        "vredmax.vs",
        "vredmaxu.vs",
        "vredmin.vs",
        "vredminu.vs",
        "vredor.vs",
        "vredsum.vs",
        "vredxor.vs",
    ],
    "VCPOP_M": [
        "vcpop.m",
    ],
    "VEXTTYPE": [
        "vsext.vf2",
        "vsext.vf4",
        "vsext.vf8",
        "vzext.vf2",
        "vzext.vf4",
        "vzext.vf8",
    ],
    "VFIRST_M": [
        "vfirst.m",
    ],
    "VFMERGE": [
        "vfmerge.vfm",
    ],
    "VFMV": [
        "vfmv.v.f",
    ],
    "VFMVFS": [
        "vfmv.f.s",
    ],
    "VFMVSF": [
        "vfmv.s.f",
    ],
    "VFNUNARY0": [
        "vfncvt.f.f.w",
        "vfncvt.f.x.w",
        "vfncvt.f.xu.w",
        "vfncvt.rod.f.f.w",
        "vfncvt.rtz.x.f.w",
        "vfncvt.rtz.xu.f.w",
        "vfncvt.x.f.w",
        "vfncvt.xu.f.w",
    ],
    "VFUNARY0": [
        "vfcvt.f.x.v",
        "vfcvt.f.xu.v",
        "vfcvt.rtz.x.f.v",
        "vfcvt.rtz.xu.f.v",
        "vfcvt.x.f.v",
        "vfcvt.xu.f.v",
    ],
    "VFUNARY1": [
        "vfclass.v",
        "vfrec7.v",
        "vfrsqrt7.v",
        "vfsqrt.v",
    ],
    "VFWUNARY0": [
        "vfwcvt.f.f.v",
        "vfwcvt.f.x.v",
        "vfwcvt.f.xu.v",
        "vfwcvt.rtz.x.f.v",
        "vfwcvt.rtz.xu.f.v",
        "vfwcvt.x.f.v",
        "vfwcvt.xu.f.v",
    ],
    "VICMPTYPE": [
        "vmseq.vi",
        "vmsgt.vi",
        "vmsgtu.vi",
        "vmsle.vi",
        "vmsleu.vi",
        "vmsne.vi",
    ],
    "VID_V": [
        "vid.v",
    ],
    "VIMCTYPE": [
        "vmadc.vi",
    ],
    "VIMSTYPE": [
        "vadc.vim",
    ],
    "VIMTYPE": [
        "vmadc.vim",
    ],
    "VIOTA_M": [
        "viota.m",
    ],
    "VISG": [
        "vrgather.vi",
        "vslidedown.vi",
        "vslideup.vi",
    ],
    "VITYPE": [
        "vadd.vi",
        "vand.vi",
        "vor.vi",
        "vrsub.vi",
        "vsadd.vi",
        "vsaddu.vi",
        "vsll.vi",
        "vsra.vi",
        "vsrl.vi",
        "vssra.vi",
        "vssrl.vi",
        "vxor.vi",
    ],
    "VLRETYPE": [
        "vl1re16.v",
        "vl1re32.v",
        "vl1re64.v",
        "vl1re8.v",
        "vl2re16.v",
        "vl2re32.v",
        "vl2re64.v",
        "vl2re8.v",
        "vl4re16.v",
        "vl4re32.v",
        "vl4re64.v",
        "vl4re8.v",
        "vl8re16.v",
        "vl8re32.v",
        "vl8re64.v",
        "vl8re8.v",
    ],
    "VLSEGFFTYPE": [
        "vle16ff.v",
        "vle32ff.v",
        "vle64ff.v",
        "vle8ff.v",
        "vlseg2e16ff.v",
        "vlseg2e32ff.v",
        "vlseg2e64ff.v",
        "vlseg2e8ff.v",
        "vlseg3e16ff.v",
        "vlseg3e32ff.v",
        "vlseg3e64ff.v",
        "vlseg3e8ff.v",
        "vlseg4e16ff.v",
        "vlseg4e32ff.v",
        "vlseg4e64ff.v",
        "vlseg4e8ff.v",
        "vlseg5e16ff.v",
        "vlseg5e32ff.v",
        "vlseg5e64ff.v",
        "vlseg5e8ff.v",
        "vlseg6e16ff.v",
        "vlseg6e32ff.v",
        "vlseg6e64ff.v",
        "vlseg6e8ff.v",
        "vlseg7e16ff.v",
        "vlseg7e32ff.v",
        "vlseg7e64ff.v",
        "vlseg7e8ff.v",
        "vlseg8e16ff.v",
        "vlseg8e32ff.v",
        "vlseg8e64ff.v",
        "vlseg8e8ff.v",
    ],
    "VLSEGTYPE": [
        "vle16.v",
        "vle32.v",
        "vle64.v",
        "vle8.v",
        "vlseg2e16.v",
        "vlseg2e32.v",
        "vlseg2e64.v",
        "vlseg2e8.v",
        "vlseg3e16.v",
        "vlseg3e32.v",
        "vlseg3e64.v",
        "vlseg3e8.v",
        "vlseg4e16.v",
        "vlseg4e32.v",
        "vlseg4e64.v",
        "vlseg4e8.v",
        "vlseg5e16.v",
        "vlseg5e32.v",
        "vlseg5e64.v",
        "vlseg5e8.v",
        "vlseg6e16.v",
        "vlseg6e32.v",
        "vlseg6e64.v",
        "vlseg6e8.v",
        "vlseg7e16.v",
        "vlseg7e32.v",
        "vlseg7e64.v",
        "vlseg7e8.v",
        "vlseg8e16.v",
        "vlseg8e32.v",
        "vlseg8e64.v",
        "vlseg8e8.v",
    ],
    "VLSSEGTYPE": [
        "vlse16.v",
        "vlse32.v",
        "vlse64.v",
        "vlse8.v",
        "vlsseg2e16.v",
        "vlsseg2e32.v",
        "vlsseg2e64.v",
        "vlsseg2e8.v",
        "vlsseg3e16.v",
        "vlsseg3e32.v",
        "vlsseg3e64.v",
        "vlsseg3e8.v",
        "vlsseg4e16.v",
        "vlsseg4e32.v",
        "vlsseg4e64.v",
        "vlsseg4e8.v",
        "vlsseg5e16.v",
        "vlsseg5e32.v",
        "vlsseg5e64.v",
        "vlsseg5e8.v",
        "vlsseg6e16.v",
        "vlsseg6e32.v",
        "vlsseg6e64.v",
        "vlsseg6e8.v",
        "vlsseg7e16.v",
        "vlsseg7e32.v",
        "vlsseg7e64.v",
        "vlsseg7e8.v",
        "vlsseg8e16.v",
        "vlsseg8e32.v",
        "vlsseg8e64.v",
        "vlsseg8e8.v",
    ],
    "VLXSEGTYPE": [
        "vloxei16.v",
        "vloxei32.v",
        "vloxei64.v",
        "vloxei8.v",
        "vloxseg2ei16.v",
        "vloxseg2ei32.v",
        "vloxseg2ei64.v",
        "vloxseg2ei8.v",
        "vloxseg3ei16.v",
        "vloxseg3ei32.v",
        "vloxseg3ei64.v",
        "vloxseg3ei8.v",
        "vloxseg4ei16.v",
        "vloxseg4ei32.v",
        "vloxseg4ei64.v",
        "vloxseg4ei8.v",
        "vloxseg5ei16.v",
        "vloxseg5ei32.v",
        "vloxseg5ei64.v",
        "vloxseg5ei8.v",
        "vloxseg6ei16.v",
        "vloxseg6ei32.v",
        "vloxseg6ei64.v",
        "vloxseg6ei8.v",
        "vloxseg7ei16.v",
        "vloxseg7ei32.v",
        "vloxseg7ei64.v",
        "vloxseg7ei8.v",
        "vloxseg8ei16.v",
        "vloxseg8ei32.v",
        "vloxseg8ei64.v",
        "vloxseg8ei8.v",
        "vluxei16.v",
        "vluxei32.v",
        "vluxei64.v",
        "vluxei8.v",
        "vluxseg2ei16.v",
        "vluxseg2ei32.v",
        "vluxseg2ei64.v",
        "vluxseg2ei8.v",
        "vluxseg3ei16.v",
        "vluxseg3ei32.v",
        "vluxseg3ei64.v",
        "vluxseg3ei8.v",
        "vluxseg4ei16.v",
        "vluxseg4ei32.v",
        "vluxseg4ei64.v",
        "vluxseg4ei8.v",
        "vluxseg5ei16.v",
        "vluxseg5ei32.v",
        "vluxseg5ei64.v",
        "vluxseg5ei8.v",
        "vluxseg6ei16.v",
        "vluxseg6ei32.v",
        "vluxseg6ei64.v",
        "vluxseg6ei8.v",
        "vluxseg7ei16.v",
        "vluxseg7ei32.v",
        "vluxseg7ei64.v",
        "vluxseg7ei8.v",
        "vluxseg8ei16.v",
        "vluxseg8ei32.v",
        "vluxseg8ei64.v",
        "vluxseg8ei8.v",
    ],
    "VMSBF_M": [
        "vmsbf.m",
    ],
    "VMSIF_M": [
        "vmsif.m",
    ],
    "VMSOF_M": [
        "vmsof.m",
    ],
    "VMTYPE": [
        "vlm.v",
        "vsm.v",
    ],
    "VMVRTYPE": [
        "vmv1r.v",
        "vmv2r.v",
        "vmv4r.v",
        "vmv8r.v",
    ],
    "VMVSX": [
        "vmv.s.x",
    ],
    "VMVXS": [
        "vmv.x.s",
    ],
    "VSETIVLI": [
        "vsetivli",
    ],
    "VSETVL": [
        "vsetvl",
    ],
    "VSETVLI": [
        "vsetvli",
    ],
    "VSRETYPE": [
        "vs1r.v",
        "vs2r.v",
        "vs4r.v",
        "vs8r.v",
    ],
    "VSSEGTYPE": [
        "vse16.v",
        "vse32.v",
        "vse64.v",
        "vse8.v",
        "vsseg2e16.v",
        "vsseg2e32.v",
        "vsseg2e64.v",
        "vsseg2e8.v",
        "vsseg3e16.v",
        "vsseg3e32.v",
        "vsseg3e64.v",
        "vsseg3e8.v",
        "vsseg4e16.v",
        "vsseg4e32.v",
        "vsseg4e64.v",
        "vsseg4e8.v",
        "vsseg5e16.v",
        "vsseg5e32.v",
        "vsseg5e64.v",
        "vsseg5e8.v",
        "vsseg6e16.v",
        "vsseg6e32.v",
        "vsseg6e64.v",
        "vsseg6e8.v",
        "vsseg7e16.v",
        "vsseg7e32.v",
        "vsseg7e64.v",
        "vsseg7e8.v",
        "vsseg8e16.v",
        "vsseg8e32.v",
        "vsseg8e64.v",
        "vsseg8e8.v",
    ],
    "VSSSEGTYPE": [
        "vsse16.v",
        "vsse32.v",
        "vsse64.v",
        "vsse8.v",
        "vssseg2e16.v",
        "vssseg2e32.v",
        "vssseg2e64.v",
        "vssseg2e8.v",
        "vssseg3e16.v",
        "vssseg3e32.v",
        "vssseg3e64.v",
        "vssseg3e8.v",
        "vssseg4e16.v",
        "vssseg4e32.v",
        "vssseg4e64.v",
        "vssseg4e8.v",
        "vssseg5e16.v",
        "vssseg5e32.v",
        "vssseg5e64.v",
        "vssseg5e8.v",
        "vssseg6e16.v",
        "vssseg6e32.v",
        "vssseg6e64.v",
        "vssseg6e8.v",
        "vssseg7e16.v",
        "vssseg7e32.v",
        "vssseg7e64.v",
        "vssseg7e8.v",
        "vssseg8e16.v",
        "vssseg8e32.v",
        "vssseg8e64.v",
        "vssseg8e8.v",
    ],
    "VSXSEGTYPE": [
        "vsoxei16.v",
        "vsoxei32.v",
        "vsoxei64.v",
        "vsoxei8.v",
        "vsoxseg2ei16.v",
        "vsoxseg2ei32.v",
        "vsoxseg2ei64.v",
        "vsoxseg2ei8.v",
        "vsoxseg3ei16.v",
        "vsoxseg3ei32.v",
        "vsoxseg3ei64.v",
        "vsoxseg3ei8.v",
        "vsoxseg4ei16.v",
        "vsoxseg4ei32.v",
        "vsoxseg4ei64.v",
        "vsoxseg4ei8.v",
        "vsoxseg5ei16.v",
        "vsoxseg5ei32.v",
        "vsoxseg5ei64.v",
        "vsoxseg5ei8.v",
        "vsoxseg6ei16.v",
        "vsoxseg6ei32.v",
        "vsoxseg6ei64.v",
        "vsoxseg6ei8.v",
        "vsoxseg7ei16.v",
        "vsoxseg7ei32.v",
        "vsoxseg7ei64.v",
        "vsoxseg7ei8.v",
        "vsoxseg8ei16.v",
        "vsoxseg8ei32.v",
        "vsoxseg8ei64.v",
        "vsoxseg8ei8.v",
        "vsuxei16.v",
        "vsuxei32.v",
        "vsuxei64.v",
        "vsuxei8.v",
        "vsuxseg2ei16.v",
        "vsuxseg2ei32.v",
        "vsuxseg2ei64.v",
        "vsuxseg2ei8.v",
        "vsuxseg3ei16.v",
        "vsuxseg3ei32.v",
        "vsuxseg3ei64.v",
        "vsuxseg3ei8.v",
        "vsuxseg4ei16.v",
        "vsuxseg4ei32.v",
        "vsuxseg4ei64.v",
        "vsuxseg4ei8.v",
        "vsuxseg5ei16.v",
        "vsuxseg5ei32.v",
        "vsuxseg5ei64.v",
        "vsuxseg5ei8.v",
        "vsuxseg6ei16.v",
        "vsuxseg6ei32.v",
        "vsuxseg6ei64.v",
        "vsuxseg6ei8.v",
        "vsuxseg7ei16.v",
        "vsuxseg7ei32.v",
        "vsuxseg7ei64.v",
        "vsuxseg7ei8.v",
        "vsuxseg8ei16.v",
        "vsuxseg8ei32.v",
        "vsuxseg8ei64.v",
        "vsuxseg8ei8.v",
    ],
    "VVCMPTYPE": [
        "vmseq.vv",
        "vmsle.vv",
        "vmsleu.vv",
        "vmslt.vv",
        "vmsltu.vv",
        "vmsne.vv",
    ],
    "VVMCTYPE": [
        "vmadc.vv",
        "vmsbc.vv",
    ],
    "VVMSTYPE": [
        "vadc.vvm",
        "vsbc.vvm",
    ],
    "VVMTYPE": [
        "vmadc.vvm",
        "vmsbc.vvm",
    ],
    "VVTYPE": [
        "vadd.vv",
        "vand.vv",
        "vmax.vv",
        "vmaxu.vv",
        "vmin.vv",
        "vminu.vv",
        "vor.vv",
        "vrgather.vv",
        "vrgatherei16.vv",
        "vsadd.vv",
        "vsaddu.vv",
        "vsll.vv",
        "vsmul.vv",
        "vsra.vv",
        "vsrl.vv",
        "vssra.vv",
        "vssrl.vv",
        "vssub.vv",
        "vssubu.vv",
        "vsub.vv",
        "vxor.vv",
    ],
    "VXCMPTYPE": [
        "vmseq.vx",
        "vmsgt.vx",
        "vmsgtu.vx",
        "vmsle.vx",
        "vmsleu.vx",
        "vmslt.vx",
        "vmsltu.vx",
        "vmsne.vx",
    ],
    "VXMCTYPE": [
        "vmadc.vx",
        "vmsbc.vx",
    ],
    "VXMSTYPE": [
        "vadc.vxm",
        "vsbc.vxm",
    ],
    "VXMTYPE": [
        "vmadc.vxm",
        "vmsbc.vxm",
    ],
    "VXSG": [
        "vrgather.vx",
        "vslidedown.vx",
        "vslideup.vx",
    ],
    "VXTYPE": [
        "vadd.vx",
        "vand.vx",
        "vmax.vx",
        "vmaxu.vx",
        "vmin.vx",
        "vminu.vx",
        "vor.vx",
        "vrsub.vx",
        "vsadd.vx",
        "vsaddu.vx",
        "vsll.vx",
        "vsmul.vx",
        "vsra.vx",
        "vsrl.vx",
        "vssra.vx",
        "vssrl.vx",
        "vssub.vx",
        "vssubu.vx",
        "vsub.vx",
        "vxor.vx",
    ],
    "WMVVTYPE": [
        "vwmacc.vv",
        "vwmaccsu.vv",
        "vwmaccu.vv",
    ],
    "WMVXTYPE": [
        "vwmacc.vx",
        "vwmaccsu.vx",
        "vwmaccu.vx",
        "vwmaccus.vx",
    ],
    "WVTYPE": [
        "vwadd.wv",
        "vwaddu.wv",
        "vwsub.wv",
        "vwsubu.wv",
    ],
    "WVVTYPE": [
        "vwadd.vv",
        "vwaddu.vv",
        "vwmul.vv",
        "vwmulsu.vv",
        "vwmulu.vv",
        "vwsub.vv",
        "vwsubu.vv",
    ],
    "WVXTYPE": [
        "vwadd.vx",
        "vwaddu.vx",
        "vwmul.vx",
        "vwmulsu.vx",
        "vwmulu.vx",
        "vwsub.vx",
        "vwsubu.vx",
    ],
    "WXTYPE": [
        "vwadd.wx",
        "vwaddu.wx",
        "vwsub.wx",
        "vwsubu.wx",
    ],
}
